footprint: [[0.22, 0.19], [0.22, -0.19], [-0.22, -0.19], [-0.22, 0.19]]

obstacle_range: 50.0
raytrace_range: 55.0

static_layer:
  enabled: true

global_inflation_layer:
  enabled: true
  inflation_radius: 1.5
  cost_scaling_factor: 20.0

local_inflation_layer:
  enabled: true
  inflation_radius: 0.5
  cost_scaling_factor: 10.0

obstacle_layer:
  enabled: true
  track_unknown_space: true
  combination_method: 0

  obstacle_range: 25.0
  raytrace_range: 30.0

  observation_sources: mid360
  mid360: {
    data_type: LaserScan,
    topic: obstacle_scan,
    sensor_frame: livox_flat,
    marking: true,
    clearing: true,
    inf_is_valid: true
  }
