local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  transform_tolerance: 5.0

  update_frequency: 5.0
  publish_frequency: 5.0

  rolling_window: true
  width: 15.0
  height: 15.0
  resolution: 0.1

  plugins:
    - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
    - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}
