shutdown_costmaps: false

oscillation_distance: 1.0
oscillation_timeout: 10.0

controller_frequency: 10.0
controller_patience: 15.0

planner_frequency: 2.0
planner_patience: 5.0
max_planning_retries: -1

recovery_behaviors: 
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'