GlobalPlanner:
  allow_unknown: true
  default_tolerance: 2.0
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false

  visualize_potential: false
  publish_potential: true

  lethal_cost: 253
  neutral_cost: 66
  cost_factor: 0.55

  orientation_mode: 0
  orientation_window_size: 1