# flag
flag_auto_start: false
flag_pure_lidar: false

# frame
frame_map: "map"
frame_odom: "odom"
frame_sensor: "livox_flat"

# init
init_position: [0.0, 0.0, 0.0]
init_orientation: [1.0, 0.0, 0.0, 0.0]

# ndt
ndt_trans_epsilon: 0.03
ndt_step_size: 0.05
ndt_resolution: 1.0
ndt_max_iterations: 30

# source
source_voxel_size: 0.3
source_fov: [-3.14, 3.14]
source_distance: [0.3, 30.0]

# target
target_voxel_size: 0.3
target_pcd_size: 40.0
target_update_distance: 20.0
